# Generated by Django 4.1 on 2022-08-31 16:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foehn", "0002_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
    ]
