# Generated by Django 4.1 on 2022-08-31 16:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foehn", "0004_turbinemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turbine",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turbines",
                        to="foehn.turbinemodel",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turbines",
                        to="foehn.site",
                    ),
                ),
            ],
        ),
    ]
