# Generated by Django 4.1 on 2022-09-01 18:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foehn", "0006_scadafile_scadafileformat_scadarecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerCurve",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("wind_speed_0ms", models.FloatField(default=0)),
                ("wind_speed_1ms", models.FloatField(default=0)),
                ("wind_speed_2ms", models.FloatField(default=0)),
                ("wind_speed_3ms", models.FloatField(default=0)),
                ("wind_speed_4ms", models.FloatField(default=0)),
                ("wind_speed_5ms", models.FloatField(default=0)),
                ("wind_speed_6ms", models.FloatField(default=0)),
                ("wind_speed_7ms", models.FloatField(default=0)),
                ("wind_speed_8ms", models.FloatField(default=0)),
                ("wind_speed_9ms", models.FloatField(default=0)),
                ("wind_speed_10ms", models.FloatField(default=0)),
                ("wind_speed_11ms", models.FloatField(default=0)),
                ("wind_speed_12ms", models.FloatField(default=0)),
                ("wind_speed_13ms", models.FloatField(default=0)),
                ("wind_speed_14ms", models.FloatField(default=0)),
                ("wind_speed_15ms", models.FloatField(default=0)),
                ("wind_speed_16ms", models.FloatField(default=0)),
                ("wind_speed_17ms", models.FloatField(default=0)),
                ("wind_speed_18ms", models.FloatField(default=0)),
                ("wind_speed_19ms", models.FloatField(default=0)),
                ("wind_speed_20ms", models.FloatField(default=0)),
                ("wind_speed_21ms", models.FloatField(default=0)),
                ("wind_speed_22ms", models.FloatField(default=0)),
                ("wind_speed_23ms", models.FloatField(default=0)),
                ("wind_speed_24ms", models.FloatField(default=0)),
                ("wind_speed_25ms", models.FloatField(default=0)),
            ],
        ),
    ]
