# Generated by Django 4.1 on 2022-09-01 18:14

import django.db.models.deletion
from django.db import migrations, models

import foehn.models


def create_powercurves(apps, schema_editor):
    TurbineModel = apps.get_model("foehn", "TurbineModel")
    PowerCurve = apps.get_model("foehn", "PowerCurve")

    for turbine_model in TurbineModel.objects.filter(
        reference_power_curve__isnull=True
    ):
        power_curve = PowerCurve.objects.create()
        turbine_model.reference_power_curve = power_curve
        turbine_model.save()


class Migration(migrations.Migration):

    dependencies = [
        ("foehn", "0007_powercurve"),
    ]

    operations = [
        migrations.AddField(
            model_name="turbinemodel",
            name="reference_power_curve",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turbine_model",
                to="foehn.powercurve",
                null=True,
            ),
        ),
        migrations.RunPython(
            create_powercurves, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="turbinemodel",
            name="reference_power_curve",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turbine_model",
                to="foehn.powercurve",
            ),
        ),
    ]
