# Generated by Django 4.1 on 2022-09-01 18:14

import django.db.models.deletion
from django.db import migrations, models

import foehn.models


def create_powercurves(apps, schema_editor):
    Turbine = apps.get_model("foehn", "Turbine")
    PowerCurve = apps.get_model("foehn", "PowerCurve")

    for turbine in Turbine.objects.filter(power_curve__isnull=True):
        power_curve = PowerCurve.objects.create()
        turbine.power_curve = power_curve
        turbine.save()


class Migration(migrations.Migration):

    dependencies = [
        ("foehn", "0008_turbinemodel_power_curve_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="turbine",
            name="power_curve",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turbine",
                to="foehn.powercurve",
                null=True,
            ),
        ),
        migrations.RunPython(
            create_powercurves, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="turbine",
            name="power_curve",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turbine",
                to="foehn.powercurve",
            ),
        ),
    ]
