# Generated by Django 4.1.2 on 2022-10-18 12:35

from django.db import migrations, models
import django.db.models.deletion
import foehn.models


class Migration(migrations.Migration):

    dependencies = [
        ("foehn", "0009_turbine_power_curve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turbine",
            name="power_curve",
            field=models.OneToOneField(
                default=foehn.models.PowerCurve,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turbine",
                to="foehn.powercurve",
            ),
        ),
        migrations.AlterField(
            model_name="turbinemodel",
            name="reference_power_curve",
            field=models.OneToOneField(
                default=foehn.models.PowerCurve,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turbine_model",
                to="foehn.powercurve",
            ),
        ),
    ]
