version: "3.11"

services:
  foehn:
    image: foehn
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://foehn:foehn@postgres/foehn

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: foehn
      POSTGRES_USER: foehn
      POSTGRES_PASSWORD: foehn